// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwebovuPmMi-xmFPWMZ6E9BeFUXMBIis4',
    appId: '1:590335448099:web:41244cfd469c2ff4b04d96',
    messagingSenderId: '590335448099',
    projectId: 'parki-maaya',
    authDomain: 'parki-maaya.firebaseapp.com',
    storageBucket: 'parki-maaya.appspot.com',
    measurementId: 'G-5DFTPWCT79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtb6t7BBdoGia3McrRlSTzNJg66Pty56o',
    appId: '1:590335448099:android:6105c74ea3a6e83eb04d96',
    messagingSenderId: '590335448099',
    projectId: 'parki-maaya',
    storageBucket: 'parki-maaya.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiIBkTJEmoYylAX8jZ8deth4jqrhIs0CU',
    appId: '1:590335448099:ios:ad11bfcf2f91ee35b04d96',
    messagingSenderId: '590335448099',
    projectId: 'parki-maaya',
    storageBucket: 'parki-maaya.appspot.com',
    iosBundleId: 'com.example.parki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiIBkTJEmoYylAX8jZ8deth4jqrhIs0CU',
    appId: '1:590335448099:ios:ef256f78394e15dab04d96',
    messagingSenderId: '590335448099',
    projectId: 'parki-maaya',
    storageBucket: 'parki-maaya.appspot.com',
    iosBundleId: 'com.example.parki.RunnerTests',
  );
}
